name: Bornovali
favicon: null
layout_spectrum: 0.8540538079105318
typography_spectrum: 0.09437912958674133
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.763665113132447
  lightness: 0.32366141956299543
  saturation: 0.3456713459454477
  rhythmicContrast: 0.2869867286644876
purpose: []
